import { NextResponse } from 'next/server'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import { createServerSupabaseClient, createServiceClient, getActiveDistilleryId } from '@/lib/supabase-server'
import { valueBarrels, type ValuationRate, type ValuationBarrel, type ValuationLine } from '@/lib/valuation'
import { uploadToR2 } from '@/lib/r2'

const SPIRIT_LABEL: Record<string, string> = {
  bourbon: 'Bourbon', tennessee_whiskey: 'Bourbon', rye_whiskey: 'Rye',
  wheat_whiskey: 'Malt Whiskey', malt_whiskey: 'Malt Whiskey', corn_whiskey: 'Bourbon',
  rum: 'Rum', neutral_spirits: 'Other', brandy: 'Other', gin: 'Other', tequila: 'Other', other: 'Other',
}

function fmtUsd(n: number) {
  return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n)
}

export async function POST() {
  const supabase = createServerSupabaseClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'unauthorized' }, { status: 401 })

  const distilleryId = getActiveDistilleryId()
  if (!distilleryId) return NextResponse.json({ error: 'no_distillery' }, { status: 400 })

  const db = createServiceClient()
  const [{ data: dist }, { data: ratesData }, { data: barrelsData }] = await Promise.all([
    db.from('distilleries').select('name, dsp_number').eq('id', distilleryId).single(),
    db.from('valuation_rates').select('*'),
    db.from('barrels').select('id, barrel_number, spirits_type, entry_date, current_wine_gallons, status').eq('distillery_id', distilleryId).neq('status', 'dumped').neq('status', 'bottled'),
  ])

  const rates = (ratesData || []) as ValuationRate[]
  const barrels: ValuationBarrel[] = (barrelsData || []).map((b: { id: string; barrel_number: string; spirits_type: string | null; entry_date: string | null; current_wine_gallons: number | null }) => ({
    id: b.id,
    barrel_number: b.barrel_number,
    spirit_type: SPIRIT_LABEL[b.spirits_type || ''] || 'Other',
    fill_date: b.entry_date,
    current_volume_gallons: b.current_wine_gallons,
  }))
  const v = valueBarrels(barrels, rates)

  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  const addPage = () => {
    const p = doc.addPage([612, 792])
    return { p, y: 750 }
  }
  let { p, y } = addPage()
  const L = 50, R = 562
  const text = (t: string, x: number, yy: number, size = 10, b = false, color = rgb(0, 0, 0)) =>
    p.drawText(t, { x, y: yy, size, font: b ? bold : font, color })
  const rule = (yy: number) => p.drawLine({ start: { x: L, y: yy }, end: { x: R, y: yy }, thickness: 0.5, color: rgb(0.7, 0.7, 0.7) })

  text('BONDED SPIRITS INVENTORY VALUATION', L, y, 14, true); y -= 16
  text(`${dist?.name || 'Distillery'}${dist?.dsp_number ? ` · DSP ${dist.dsp_number}` : ''}`, L, y, 10); y -= 12
  text(`Generated: ${today}`, L, y, 9, false, rgb(0.4, 0.4, 0.4)); y -= 18

  rule(y); y -= 14
  text(`Total estimated value:`, L, y, 11, true)
  text(fmtUsd(v.total_value), 400, y, 11, true, rgb(0.73, 0.45, 0.09)); y -= 14
  text(`Barrels: ${v.barrel_count}    Gallons: ${v.total_gallons.toFixed(1)}    Avg age: ${(v.avg_age / 12).toFixed(1)}yr`, L, y, 10); y -= 14
  rule(y); y -= 18

  const disclaimer = 'This valuation is for insurance and financial planning purposes only and is based on current market rate estimates. Values are not guaranteed by Still / RPR Development LLC.'
  text(disclaimer, L, y, 8, false, rgb(0.4, 0.4, 0.4)); y -= 22

  text('Barrel #', L, y, 9, true)
  text('Type', L + 80, y, 9, true)
  text('Fill date', L + 170, y, 9, true)
  text('Age (mo)', L + 240, y, 9, true)
  text('Gallons', L + 310, y, 9, true)
  text('Rate', L + 380, y, 9, true)
  text('Value', L + 440, y, 9, true)
  y -= 4; rule(y); y -= 12

  for (const l of v.lines as ValuationLine[]) {
    if (y < 80) {
      const next = addPage(); p = next.p; y = next.y
    }
    text(l.barrel_number.slice(0, 14), L, y, 8)
    text(l.spirit_type.slice(0, 14), L + 80, y, 8)
    text(l.fill_date || '—', L + 170, y, 8)
    text(String(l.age_months), L + 240, y, 8)
    text(l.gallons.toFixed(1), L + 310, y, 8)
    text(`$${l.rate_per_gallon.toFixed(2)}`, L + 380, y, 8)
    text(fmtUsd(l.estimated_value), L + 440, y, 8)
    y -= 12
  }
  rule(y); y -= 14
  text('TOTAL', L, y, 9, true)
  text(v.total_gallons.toFixed(1), L + 310, y, 9, true)
  text(fmtUsd(v.total_value), L + 440, y, 9, true)

  // Footer
  text(`Generated by Still — barrel-tracker.vercel.app | ${today}`, L, 30, 8, false, rgb(0.5, 0.5, 0.5))

  const pdfBytes = await doc.save()
  const key = `valuations/${distilleryId}/${Date.now()}.pdf`
  const url = await uploadToR2(key, Buffer.from(pdfBytes), 'application/pdf')

  const { data: snap, error } = await db.from('valuation_snapshots').insert({
    distillery_id: distilleryId,
    total_value: v.total_value,
    barrel_count: v.barrel_count,
    total_gallons: v.total_gallons,
    generated_by: user.id,
    pdf_url: url,
  }).select().single()
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  return NextResponse.json({ snapshot: snap, pdf_url: url, summary: v })
}
